/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.atomev8.component;

import com.atomev8.swing.PictureBox;
import com.atomve8.event.PublicEvent;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.SwingUtilities;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author CP-20MAB
 */
public class ChatImage extends javax.swing.JLayeredPane {

    /**
     * Creates new form ChatImage
     */
    public ChatImage(boolean right) {
        initComponents();
        setLayout(new MigLayout("","0["+(right?"right":"left")+"]0","0[]0"));
    }
    
    public void addImage(Icon ...images){
        for(Icon image :images){
            PictureBox pic = new PictureBox();
            pic.setPreferredSize(getAutoSize(image, 200,200));
            pic.setImage(image);
            addEvent(pic, image);
            add(pic, "wrap");
        }
    }
    
    private void addEvent(Component comp, Icon image){
        comp.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        comp.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent event){
                if(SwingUtilities.isLeftMouseButton(event)){
                    PublicEvent.getInstance().getEventImageView().viewImage(image);
                }
            }
        });
    }
    
    private Dimension getAutoSize(Icon image, int w, int h) {
        int iw = image.getIconWidth();
        int ih = image.getIconHeight();
        double xScale = (double) w / iw;
        double yScale = (double) h / ih;
        double scale = Math.min(xScale, yScale);
        int width = (int) (scale * iw);
        int height = (int) (scale * ih);
        int x = (w - width) / 2;
        int y = (h - height) / 2;
        return new Dimension(width, height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
